### ISSUE TITLE
Adding time to task removes all other block properties

### ISSUE THREAD

**Issue by prashantsengar** [haydenull/logseq-plugin-agenda#72]
What happens: If you add time to a task in the calendar view, it will remove all the block properties.

## To Reproduce

Create a task
```
TODO do something 
date:: [[Jun 26th, 2022]] 
project:: [[Test Project]] 
```

* Go to calendar view
* Set "All Day" to "No"
* Set the "start" and "end" time of the task
* Click OK

The task becomes
`TODO 00:02-00:32 do something`

## Expected behaviour

Task should contain the original block properties

```
TODO 00:02-00:32 do something
date:: [[Jun 26th, 2022]] 
project:: [[Test Project]] 
```

**Comment by WizardNo7** [comment]
Hi @haydenull, I'm not sure if you've recently re-looked at this bug, but it is _severely hampering_ the ability to track Project tasks from the Journal or anywhere that isn't the "Project page", going against the general intended Logseq flow.

I think it is a fairly _critical_, **core-feature** breaking bug.

Thanks in advance! 🙏

**Comment by haydenull** [comment]
I apologize for the delay in my response. The reason for my delay was that I was waiting for official API to improve.

However, considering that this problem is quite serious for some people, I will temporarily fix it using some less concise methods.

It can be expected that the issue will be fixed in the new version, which will be released in one day.

**Comment by haydenull** [comment]
Yout can try version 1.5.2 to see if it solves this issue. Please feel free to let me know if you encounter any problems.
